name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd apps/web
        npm install

    - name: Build project
      run: |
        cd apps/web
        NEXT_PUBLIC_DYNAMIC_ENV_ID=${{ vars.NEXT_PUBLIC_DYNAMIC_ENV_ID }} npm run build
      env:
        NEXT_PUBLIC_DYNAMIC_ENV_ID: ${{ vars.NEXT_PUBLIC_DYNAMIC_ENV_ID }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: apps/web/out 